// Generated by CoffeeScript 1.3.1
(function() {

  window.Capybara || (window.Capybara = {});

  Capybara.SpecGenerator = (function() {

    SpecGenerator.name = 'SpecGenerator';

    SpecGenerator.prototype.lines = [];

    function SpecGenerator() {}

    SpecGenerator.prototype.addLine = function(data) {};

    SpecGenerator.prototype.generate = function() {};

    return SpecGenerator;

  })();

}).call(this);
