// Generated by CoffeeScript 1.3.1
(function() {
  var changeToNextState, listener, specs, state, states;

  specs = null;

  state = 'off';

  states = 'capture.actions capture.matchers generate off'.split(' ');

  changeToNextState = function(tab) {
    var output;
    state = states[_.indexOf(states, state) + 1] ||  _.first(states);
    chrome.tabs.sendRequest(tab.id, {
      state: state,
      tabURL: tab.url
    }, function() {});
    chrome.browserAction.setIcon({
      path: "images/button_" + (state.replace('.', '_')) + ".png",
      tabId: tab.id
    });
    switch (state) {
      case 'capture.actions':
        return specs = new Capybara.Specs({
          tabURL: tab.url
        });
      case 'generate':
        output = specs.generate();
        $('#clipboard').val(output).focus().select();
        return document.execCommand('copy');
    }
  };

  chrome.browserAction.onClicked.addListener(changeToNextState);

  listener = function(request, sender, sendResponse) {
    switch (request.name) {
      case 'captured':
        return specs.add(request.data);
    }
  };

  chrome.extension.onRequest.addListener(listener);

}).call(this);
