// Generated by CoffeeScript 1.3.1
(function() {
  var buttonListener, findOrCreateTabProcess, processes, tabsListener;

  processes = {};

  findOrCreateTabProcess = function(tab) {
    var process;
    process = processes[tab.id];
    if (process == null) {
      process = new TabProcess({
        tab: tab,
        onStateChange: function(state) {
          chrome.tabs.sendRequest(tab.id, {
            state: state
          });
          return chrome.browserAction.setIcon({
            path: "images/button_" + (state.replace('.', '_')) + ".png",
            tabId: tab.id
          });
        }
      });
      processes[tab.id] = process;
    }
    return process;
  };

  tabsListener = function(request, sender, sendResponse) {
    var process;
    process = findOrCreateTabProcess(sender.tab);
    switch (request.name) {
      case 'captured':
        return process.specs.add(request.data);
      case 'loaded':
        return process.setState;
    }
  };

  chrome.extension.onRequest.addListener(tabsListener);

  buttonListener = function(tab) {
    var output, process;
    process = findOrCreateTabProcess(tab);
    process.toNextState();
    switch (process.getState()) {
      case 'generate':
        output = process.specs.generate();
        $('#clipboard').val(output).focus().select();
        return document.execCommand('copy');
    }
  };

  chrome.browserAction.onClicked.addListener(buttonListener);

}).call(this);
