// Generated by CoffeeScript 1.3.1
(function() {
  var changeToNextState, listener, state, states;

  state = 'off';

  states = 'recording confirming printing off'.split(' ');

  changeToNextState = function(tab) {
    state = states[_.indexOf(states, state) + 1] ||  _.first(states);
    chrome.tabs.sendRequest(tab.id, {
      state: state,
      tabURL: tab.url
    }, function() {});
    return chrome.browserAction.setIcon({
      path: "images/button_" + state + ".png",
      tabId: tab.id
    });
  };

  chrome.browserAction.onClicked.addListener(changeToNextState);

  listener = function(request, sender, sendResponse) {
    var $textarea;
    switch (request.name) {
      case 'copy':
        $textarea = $('#clipboard').val(request.text).focus().select();
        return document.execCommand('copy');
      case 'captured':
        return console.log('captured:', request);
    }
  };

  chrome.extension.onRequest.addListener(listener);

}).call(this);
