// Generated by CoffeeScript 1.3.1
(function() {

  jasmine.getFixtures().fixturesPath = 'fixtures/capybara/recorders';

  describe('Capybara actions recorder', function() {
    var recorder;
    loadFixtures('actions_spec.html');
    recorder = null;
    beforeEach(function() {
      return recorder = new Capybara.Recorders.Actions;
    });
    describe('#start', function() {
      return it('should attach events', function() {
        console.log($('#jasmine-fixtures'));
        return expect($('#input-file')).toHandle('change.actionrecorder');
      });
    });
    return describe('#stop', function() {
      return it('should detach events', function() {});
    });
  });

}).call(this);
