// Generated by CoffeeScript 1.3.1
(function() {
  var LocatorGenerator;

  LocatorGenerator = (function() {

    LocatorGenerator.name = 'LocatorGenerator';

    function LocatorGenerator() {}

    LocatorGenerator.prototype.generate = function($el, methods) {
      var _this = this;
      if (methods == null) {
        methods = ['id'];
      }
      return _.compact(_.map(methods, function(method) {
        return _this[method]($el);
      }))[0];
    };

    LocatorGenerator.prototype.id = function($el) {
      var id;
      if ((id = $el.attr('id')) != null) {
        return id;
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype.name = function($el) {
      var name;
      if ((name = $el.attr('name')) != null) {
        return name;
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype.label = function($el) {
      var $label;
      if (($label = this._findLabelForInput($el)) != null) {
        return $.trim($label.text());
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype.text = function($el) {
      var text;
      if ((text = $.trim($el.text())).length) {
        return text;
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype.value = function($el) {
      var value;
      if ((value = $.trim($el.val())).length) {
        return value;
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype.imgAlt = function($el) {
      var $img;
      $img = $el.find('img:first');
      if ($img.length) {
        return $img.attr('alt');
      } else {
        return null;
      }
    };

    LocatorGenerator.prototype._findLabelForInput = function($input) {
      var $label;
      $label = $("label[for=" + ($input.attr('id')) + "]");
      if (!$label.length) {
        $label = $input.closest('label');
      }
      if ($label.length) {
        return $label;
      } else {
        return null;
      }
    };

    return LocatorGenerator;

  })();

  window['LocatorGenerator'] = LocatorGenerator;

}).call(this);
