// Generated by CoffeeScript 1.3.1
(function() {
  var STATES, TabProcess;

  STATES = ['name', 'capture.actions', 'capture.matchers', 'generate', 'off'];

  TabProcess = (function() {

    TabProcess.name = 'TabProcess';

    TabProcess.prototype.id = null;

    TabProcess.prototype.state = null;

    function TabProcess(options) {
      this.id = options.tab.id;
      this.state = 'off';
      this.stateChangeCallback = options.onStateChange;
      this.specs = new Capybara.Specs({
        tabURL: options.tab.url
      });
    }

    TabProcess.prototype.getState = function() {
      return this.state;
    };

    TabProcess.prototype.getInfo = function() {
      return {
        state: this.getState(),
        isNamed: this.specs.name != null
      };
    };

    TabProcess.prototype.setState = function(state) {
      this.state = state;
      return this.stateChangeCallback(this.state);
    };

    TabProcess.prototype.toNextState = function() {
      var state;
      state = STATES[_.indexOf(STATES, this.state) + 1] ||  _.first(STATES);
      return this.setState(state);
    };

    TabProcess.prototype.kill = function() {
      return delete this.specs;
    };

    return TabProcess;

  })();

  window.TabProcess = TabProcess;

}).call(this);
